--- # ERROR HANDLING EXAMPLE
- hosts: appserver
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: Execute a command that will fail
      command: /bin/false
      ignore_errors: yes
    - name: Install telnet
      yum: pkg=telnet state=latest
