---
- hosts: web
  become: yes
  gather_facts: True 
  connection: ssh
  vars:
    playbook_version: 0.1b
  vars_files:
    - conf/variable.yml
  tasks:
    - name: Install HTTPD
      action: yum name={{package_name}} state=installed
      notify: 
        - Restart HTTPD
  handlers:
    - name: Restart HTTPD
      shell: service name=httpd state= restarted
      
