--- # FULL INCLUDE TASKS EXAMPLE
- hosts: appserver
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - include: plays/packages.yml
    - name: Verify the telnet package is installed
      raw: yum list installed | grep telnet > /opt/pkgs.log
