--- # outline to palybook translation
- hosts: web
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: date/time stamp when the playbook start
      raw: /usr/bin/date > /home/palybook_start.log

    - name: install the apache web server
      yum: pkg=httpd state=latest

    - name: start the web service
      shell: service name=httpd start=restarted
    
    - name: verify that web service is running
      command: systemctl status httpd
    
    - debug: var=result
    
    - name: install client software
      yum: pkg=telnet state=latest
      yum: pkg=lynx state=latest

    - name: log all the packages install on the system
      raw: yum list installed > /home/installed.log
    
    - name: data/time stamp for when the playbook ends
      raw: /usr/bin/date > /home/palybook_end.log


